# Generated by Django 4.1.1 on 2022-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_flatowner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatowner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
